// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfK_vcOylKbBsy3rRzPtGAnwWunG8QIGQ',
    appId: '1:585045173412:web:eee5c43d89a05026ca7231',
    messagingSenderId: '585045173412',
    projectId: 'cooking-book-bc546',
    authDomain: 'cooking-book-bc546.firebaseapp.com',
    storageBucket: 'cooking-book-bc546.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJD7W4FoPqLabEfmT-nK9MDwQITqcgaKI',
    appId: '1:585045173412:android:f3b58a5dcc64444dca7231',
    messagingSenderId: '585045173412',
    projectId: 'cooking-book-bc546',
    storageBucket: 'cooking-book-bc546.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwSnr1ZYj-BDWL8rwT1Ju3ibw1_eoHBSg',
    appId: '1:585045173412:ios:ac29364d5d5055f9ca7231',
    messagingSenderId: '585045173412',
    projectId: 'cooking-book-bc546',
    storageBucket: 'cooking-book-bc546.appspot.com',
    iosClientId: '585045173412-fnbdvminigcogfm5n83un9ao3qufdin0.apps.googleusercontent.com',
    iosBundleId: 'com.makarov.cookingBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwSnr1ZYj-BDWL8rwT1Ju3ibw1_eoHBSg',
    appId: '1:585045173412:ios:ac29364d5d5055f9ca7231',
    messagingSenderId: '585045173412',
    projectId: 'cooking-book-bc546',
    storageBucket: 'cooking-book-bc546.appspot.com',
    iosClientId: '585045173412-fnbdvminigcogfm5n83un9ao3qufdin0.apps.googleusercontent.com',
    iosBundleId: 'com.makarov.cookingBook',
  );
}
